### ISSUE TITLE
Treat device stats as a device node

### ISSUE THREAD

**Issue by hspaaij** [homieiot/convention#100]
Currently device stats describes the status of a device. 
How is the device status different from any other node and would it make sense to use the node type to describe the device status?

Thanks

**Comment by fermuch** [comment]
I'm unsure if I understand your question...

```
homie/device-id/$state →  "ready"
```

That means the device is ready to operate. Normally you'd wait until the device sets itself to `ready` before sending him anything. Both `$state` and `$stats` work like a node, but are special hard-coded values. Every device should report its $state, and every device should set a last will topic to update $state in case they are offline.

**Comment by fermuch** [comment]
Ah, yeah. `$stats` are like a node, but a special one. They provide useful info about the device state, inside a common namespace, which makes it easier to integrate devices you don't have control over.
Imagine you download an image for an esp8266 with homie precompiled, and you're building a SuperPanel® for homie. With `$stats` you're sure what they'll be, but using nodes you might not be sure of what they represent (what node id do they use? is the temperature property called temp or temperature?). `$stats` works as a standarized way to provide device stats.

 For my projects I treat them as nodes with pre-defined values.

There's some work to set most of these values as optional ( #45 ).

**Comment by hspaaij** [comment]
Thanks for the clarification and for the quick reply.

Maybe stats could be the node id that contains these statistics as node attributes. It only needs to be a single node. 

Standardizing the names for attributes like temperature is also important. If nodes can chose different names for the same thing it will be difficult for the clients to understand them. If it is a problem for interpreting the device status then it is also going to be a problem for interpreting the nodes.

My main motivation is that on the consumer side I'd like to view the device status using the same logic as for viewing other nodes. 

Either way, I'm grateful someone is taking the effort to standardize this stuff. A common language is going to be very helpful in building a community around IoT based on MQTT without duplicating effort.
Keep up the good work!

**Comment by ThomDietrich** [comment]
One of the main design aspects of Homie lie in the difference between attributes (`$`-topics) and all other elements (non-`$`-topics)

* base, devices, nodes, properties, `/set`: These topics are for the end user / consumer and contain the actual data and offer interaction
* attributes (`$`-topics): These topics provide metadata for automatic discovery by Homie compliant controllers.

The latter are only interesting for you if you utilize a compliant controller or intend to implement one.

**Comment by hspaaij** [comment]
Thank you for explaining.
I guess there is nothing stopping me from publishing devices status as a node in addition to stats. That might be the easiest approach. Sounds like they serve different purposes.
Thanks again,

**Comment by timpur** [comment]
@ThomDietrich 
There has been talk about implementing device stats as a node format before. This would greatly improve discovery of the stats and allows the user to add additions as they see fit ?

We can still have defined stats as per convention, but we can also have additional ones that the user wants.

**Comment by ThomDietrich** [comment]
@timpur you and a few others have talked a lot about the stats recently. I honestly don't know what this is all about anymore. Could you please create a dedicated issue?

**Comment by timpur** [comment]
Yeah will do :)
