### ISSUE TITLE
Homie-Statistical-Values

### ISSUE THREAD

**Issue by timpur** [homieiot/convention#102]
There has been talk if we should implement device stats as a node. The Mian reason (IMHO) is so that the user can add there own device sensor out side of the spec, and these stats would automatically be discoverable. 

We could leave the spec as is, recommending the most common stats, but also recommend implentations implent stats as a node if they like. 

I'm not sure of the solution, but I like the idea, as I don't want to be adding every possible stat to the convention.... (Over time)

**Comment by ThomDietrich** [comment]
Hey,
could you please summarize what counts as "device stats" and why we need it? Why is an extension needed?

**Comment by davidgraeff** [comment]
Any user defined (probably read-only) property serves as a "statistic value". It probably makes sense to define some "$type"s instead like "battery" etc.

**Comment by timpur** [comment]
So currently in 3.0 we have a section defined as `Device Statistics`, this included stats like:
* $stats/signal
* $stats/cputemp
* $stats/freeheap
* ...


The spec, doesn't specify if this is or isnt open to users or implementation to add there own device stat or not. The issue is, if it is locked down then over time will have request to add more and more stats... and if it is open for user or implementation to add there own, then how do we auto discover these dynamic stats? My proposal is to just have a these implemented as a node, which comes with property discoverabilty, with unit and format ect....

**Comment by davidgraeff** [comment]
To resurrect this old topic: Is everybody d'accord to remove $stats for 4.0 and reintroduce it in a different form (probably via extension?)?

**Comment by timpur** [comment]
@davidgraeff sounds good, lets come up with an extension

**Comment by arjanmels** [comment]
I think the arguments to limit the $stats section are sound.
One feature that will also be lost however, is the heartbeat (removal of $stats/interval $stats/uptime).

How will online/offline detection be handled going forward?

**Comment by davidgraeff** [comment]
> How will online/offline detection be handled going forward?

MQTT last will.

**Comment by arjanmels** [comment]
@davidgraeff Thanks, that is indeed a clean solution.

**Comment by EP-u-NW** [comment]
With the specification of the stats extension in #171, what further steps need to be taken to close this issue?

**Comment by davidgraeff** [comment]
@timpur Please reopen if necessary
