### ISSUE TITLE
How to know the age of the information

### ISSUE THREAD

**Issue by hspaaij** [homieiot/convention#103]
When connecting a client, the the last known retained properties are send to the client. How does a client know how old this information is?

The convention contains an attribute uptime, but I can't find an attribute that describes the timestamp of this uptime.

Use cases where a timestamp is useful:
- A node is down. A client connects and can see this from the $state and likes to indicate how long the node was down for.
- A node reports very infrequently. How to tell when the information was last updated?
- Uptime is the time since the last time a sensor updated its information. How to know when that was?

Any insights would be greatly appreciated.

**Comment by ingoogni** [comment]
#53 is a proposal, though with the current ESP8266 it can be done already/.

**Comment by hspaaij** [comment]
Thank you for the feedback.

As an FYI, I'm working on a openzwave binding (in golang, using goopenzwave) that is (hopefully) homie compliant. There can be lots of nodes and it is important to identify the onces that are offline, for example when the battery ran out.

It is tricky indeed to do this right. It can't be required for the reason @timpur points out. Yet there are cases where the information is useful. Node red looks awesome but it its quite the dependency to add just to identify when a node went offline.

I don't quite understand how using interval solves this but I disagree that a timestamp without an interval is useless. The interval makes it more useful as it can be used to determine if the last update time is overdue. The use-cases listed revolve around clients that just connected and don't have a history, eg they depend on information provided by 'retained' to obtain state.

Using an attribute for timestamp is not ideal either as it requires a separate message which increases the number of messages significantly. Yet it seems to be in line with the philosophy for this convention.  What I'll do is create a node attribute called 'updated' to indicate when it was recently updated.
eg /home/<deviceID>/<nodeID>/updated = "2018-05-07T02:47:01Z"

I propose to make this a convention, eg $updated as an optional attribute, but being new to this project this might be out of line, so take it as a suggestion of a noob please :)

Thanks again,

**Comment by timpur** [comment]
@hspaaij, if your building a binding, id just show the last received message for that device. Just build it into the binding, i know its not nice, but i don't see timestamps becoming part of homie as a required thing for the reason that its not available to microcontrollers and should be forced to be required. 

I am also building a autodiscovery binding for homie atm in python for HA, my recommendations to you  any anyone else building a autodiscovery binding, are read the doc im about to publish 'recommendations when building a autodiscovery binding' :P also build the Homie binding logic as a separate lib that is not dependent on anything but the mqtt lib. This allows for others to use the binding directly in their own projects and any new platforms. 

Not sure how you do this over z-wave, but interested to hear :)

**Comment by davidgraeff** [comment]
`timestamp = currentHostTimeInS() + ( homie/device/$stats/uptime / homie/device/$stats/interval * 60)`

**Comment by ingoogni** [comment]
Sorry, my answer was completely off, misunderstood the question completely.

Can you tweak a broker to publish a 'recived' timestamp along with retained messages?

**Comment by hspaaij** [comment]
@ingoogni, Yes ideally the broker could track it as part of retained messages. That would be ideal but probably a bit harder to standardize on.
@davidgraeff Understood, it can't be a required attribute as not all devices have a timer. Although I wonder how many small devices without timer would be able to run an IP stack. 

In my case where a computer runs a binding that connects via a hub of some sort (like for example a Z-Wave stick), the node (Z-Wave sensor) also doesn't have a timer. The binding adds the timestamp when receiving node sensor data from the hub. It would be nice to have some sort of standard rather than roll my own convention for timestamp.

Thanks for the discussion. Appreciate the feedback.

**Comment by ingoogni** [comment]
To keep the broker untouched, another option could be to write a small client that listens to the original message and either inserts a TS at a certain point in the topic string and your client only listens to the modified topic. Or that small client just creates an extra topic with the TS as if it were coming from the Homie device .

Sensor+Homie --> broker ---> TS_client ---> broker ---> your client

@davidgraeff 's solution is the simplest if it fits your needs.

**Comment by timpur** [comment]
@hspaaij, sadly i don't think this will be considered to be added as part of the convention, at lest not a required field, you can push for it to be added as non required but for now i'm just going to close this.
