### ISSUE TITLE
Version 3.0.0 wrongly reported as 3.x.x

### ISSUE THREAD

**Issue by nicola-lunghi** [homieiot/convention#105]
See version number

https://github.com/homieiot/convention/tree/v3.0.0

Version: 3.x.x • Browse Versions…

**Comment by fermuch** [comment]
The x's are supposed to mean "any number". It's meant to be read as `≥3.0.0 && <4.0.0`. All  versions inside the major version 3 go inside that branch.

**Comment by nicola-lunghi** [comment]
ok but this is on the v3.0.0 tag and release not on the main branch.

**Comment by ThomDietrich** [comment]
tags simply "mark" a certain point in development. There is no direct way to add specific changes to a tag (without another commit, which would yet again be part of the actual branch).

The idea behind the x's is exactly like @fermuch described it. Not sure how we could do a better job.

**Comment by nicola-lunghi** [comment]
the x are simply a bad idea because if for example you change something in
3.1.0 you have two documents that says different things.
instead normally you increase the version in the commit that closes the
release and tag that commit.
for example:

release homie 3.0.0 (tag v3.0.0)

change the release number

-Homie release 2.9.9
+homie release 3.0.0

**Comment by nicola-lunghi** [comment]
after that you start the new release cycle like with another commit:

start of 3.1

-homie 3.0.0
+homie 3.1.0-pre0

or beta or alpha
in that way you can start adding the good ideas as a commit and when you
reach the release you tag again

is not bad to do a lot of small commits you know?

**Comment by ThomDietrich** [comment]
Yes okay but who does that work all the time, consistently without error even once? 
The x's effectively release us from that whole burden.
The knowledge which version you are browsing is implicitly clear due to the tag/branch you are browsing... no need to even mention it in the document.

**Comment by nicola-lunghi** [comment]
so I can send

homie/super-car/$homie → "3.x.x" ?

**Comment by davidgraeff** [comment]
Actually Nicola made a point here. It is indeed common to specify a version, develop, tag the release accordingly at some point and a follow up commit bumps the version.

**Comment by ThomDietrich** [comment]
That's something different. Actually tagging the git history is indeed what we agreed on. Since tag v3.0.0 there were two commits that justify a version increment. We did not yet discuss who is responsible for that step.

Regarding the "3.x.x" string in the document: No one wants to make sure it is correctly updated every time a new PR is merged to master. I'd not change anything there. We should concentrate on consistently tagging the git history, which brings us back to the whole discussion around breaking changes and "Homie core".

Besides: @marvinroger was thinking about a webpage generated from the homie repository. To be able to present precise version information there I did add placeholders: https://github.com/homieiot/convention/pull/71/files#diff-04c6e90faac2675aa89e2176d2eec7d8R6 - at least something in the direction of the request by @nicola-lunghi

**Comment by davidgraeff** [comment]
@ThomDietrich @marvinroger Can this be closed? With a homepage for the convention, the version string "3.x.x" is not part of the document anymore.

**Comment by boc-tothefuture** [comment]
@davidgraeff Can you clarify what you mean by 

> With a homepage for the convention, the version string "3.x.x" is not part of the document anymore.

Looking at the current readme.md, I am still confused in my client implementation about what version of the protocol a client should send after looking at the readme.

**Comment by davidgraeff** [comment]
The version 3.x.x is placeholder in the current readme and will probably stay this way.
It is too dangerous and leads to inconsistency  (multiple concurrent PRs...).
But for a processed homepage, the placeholder can be replaced by an actual version.

**Comment by marvinroger** [comment]
For information, @davidgraeff did an awesome job for the website, that is now deployed: https://homieiot.github.io/

**Comment by marvinroger** [comment]
@davidgraeff @ThomDietrich please prefix every PR squash commit with:

* `BREAKING: The commit message` for breaking commits (MAJOR bumped)
* `feature: The commit message` for new features commits (MINOR bumped)
* `fix: The commit message` for fixes (PATCH bumped)

This will allow the CI script to determine which version to release. 😃

**Comment by davidgraeff** [comment]
I have added a "#fix" to my commit message. Ok, I'll redo the message. A prefix is alright as well.

**Comment by timpur** [comment]
@davidgraeff , like the new website :) nice work. Shall we also add a link to it in the description of the repo ?

![image](https://user-images.githubusercontent.com/7701482/47679883-66b17880-dc19-11e8-92c0-e70528b9717c.png)

**Comment by davidgraeff** [comment]
Yup, I have created an issue.

**Comment by davidgraeff** [comment]
I thing this issue is now fixed with the website being the source of truth for reading the specification. The develop branch of this repo will continue to have a placeholder version number.
