### ISSUE TITLE
One device with one process per node. How to handle $state?

### ISSUE THREAD

**Issue by tobylorenz** [homieiot/convention#106]
I use an A20-OLinuXino-LIME2 to check my heat pump, electric power consumptions, and some other sensor values. Each of these measurements is taken with an own process on that Linux system, and each of them can be started/stopped at any time.

So actually I don't need a $state for the device (A20), but I need a $state for each of its nodes. This is not handled by the standard today. So, what is the recommended solution here? Or do we need to extend the standard?

**Comment by tobylorenz** [comment]
Then how can I ensure that the node's data is current (all data is retained), when I don't have a $state (=ready) to check it. Only the device has a state, but the node hasn't, right?

**Comment by lorenwest** [comment]
Right - my bad. Devices have $online state, nodes don't.

Nodes are just namespaces for grouping attributes within the device. Some Homie implementations will represent a node as an object, but all nodes and attributes share the state of the device.

In your case you have several things that could be up and down independently, so those different things are different devices. The device has an $online state, and a bunch of built-in attributes as well as the attributes you choose to group within one or more nodes within the device.

If the devices/{device}/$online state is true, then all retained properties for that device are fresh.

**Comment by tobylorenz** [comment]
Ok, so my processes are independent devices. Of course, they will all have the same device attributes, e.g. same $localip, same $mac. It kind of makes sense, especially when I decide to shift processes=devices later to another PC to distribute the load.

So, thanks for your help!
