### ISSUE TITLE
Sensor last read timestamp

### ISSUE THREAD

**Issue by snikch** [homieiot/convention#11]
I think that it would be great to know the last 'set' time of a sensor. Currently I'm having issues with a device where the temperature is having issues reading, however since I only send the temperature when I get a read, it's hard to know when my device is "stalled". The wifi / mqtt connection is all good, but it would be great to know approximately how stale the data in the retained mqtt topics is.

**Comment by Nzbuu** [comment]
Feels like it's up to the particular device to provide it if it's available.

If you need a standard heartbeat, then you can use the "uptime" value instead.

**Comment by snikch** [comment]
Ah, I hadn't realised there's no `now()` available on the ESP8266. I guess using the `uptime` value would suffice, but still published on a sensor data topic e.g. `devices/my_device/my_sensor/$uptime` so that I can differentiate between "device is up and connected ok" and "device sensor is submitting readings".

Does this sound at all valuable? I can implement this outside of the homie framework but it's come up as something that felt like it should be "free" (i.e. part of the framework).

**Comment by snikch** [comment]
Any thoughts on this? Happy to close it if nobody thinks it's relevant. I've added this in to my local copy of homie-esp8266 and it's already been invaluable.

![image](https://cloud.githubusercontent.com/assets/115958/19757465/7fbd35d4-9c7f-11e6-8f60-0cb594a10e35.png)

**Comment by marvinroger** [comment]
Given the fact that there's no feedback, I guess we can close this. 😉

**Comment by snikch** [comment]
:) happy to close it if you think there's no value. I've personally found it incredibly valuable as my devices are very unstable when running homie-esp8266 with DHT11 sensors (hard to get more than an hours uptime, and sensors often fail to read), and this allows me to track how stale the sensor data is. I'll see if I can implement the feature without having to hack the homie-esp8266 core.

Cheers

**Comment by nerdfirefighter** [comment]
I know this is an old thready but can't you just define another property for your temp node that is called settime which could contain the $uptime when the property was last set?

**Comment by ingoogni** [comment]
have the node publish an measurement $interval, have the client check whether the data is coming outside the expected interval.
#54

**Comment by ThomDietrich** [comment]
An observing controller will be aware of the arrival time of a message and can track this information accordingly. An exception is the moment when a controller connects to the broker and receives retained messages. Sadly those messages do not provide a timestamp with them. If the client is online and working, it is its task to keep properties correct and updated. Imho the convention doesn't have to do anything here.

In the described troubleshooting case, in which a sensor/client is having system issues, the problem should either be solved or bypassed, e.g. by fixing the sensor or by adding an additional property for the last-update-timestamp as suggested by @nerdfirefighter - which is well inside the current convention.

Closing as nothing has to be done here
