### ISSUE TITLE
Confusion on device/$state message order

### ISSUE THREAD

**Issue by boc-tothefuture** [homieiot/convention#111]
The documentation states (Emphasis is mine):

> init: this is the state the device is in when it is connected to the MQTT broker, but has not yet sent all Homie messages and is not yet ready to operate. **This is the first message** that must that must be sent.

The example right above it shows:

> homie/super-car/$homie → "2.1.0"
homie/super-car/$name → "Super car"
homie/super-car/$localip → "192.168.0.10"
homie/super-car/$mac → "DE:AD:BE:EF:FE:ED"
homie/super-car/$fw/name → "weatherstation-firmware"
homie/super-car/$fw/version → "1.0.0"
homie/super-car/$nodes → "wheels,engine,lights[]"
homie/super-car/$implementation → "esp8266"
homie/super-car/$stats/interval → "60"
homie/super-car/$state → "ready"

Based on how I interpret the documentation, the example should be:

```
homie/super-car/$state → "init"
homie/super-car/$homie → "2.1.0"
homie/super-car/$name → "Super car"
homie/super-car/$localip → "192.168.0.10"
homie/super-car/$mac → "DE:AD:BE:EF:FE:ED"
homie/super-car/$fw/name → "weatherstation-firmware"
homie/super-car/$fw/version → "1.0.0"
homie/super-car/$nodes → "wheels,engine,lights[]"
homie/super-car/$implementation → "esp8266"
homie/super-car/$stats/interval → "60"
homie/super-car/$state → "ready"
```
But then it seems odd to send the state before the version of the protocol?  Is the documentation off or am I interpreting this incorrectly?

**Comment by lorenwest** [comment]
Great eagle-eye. If there is to be value in `$state` having both `init` and `ready` values, I think it should be documented to be the 2nd post-connect message, with `$homie` version being the first.

If `$homie` version is output first, that gives us the ability to understand the meaning of `$state`, and even have the opportunity to change it in future versions. 

Not that we would, but we could.

**Comment by davidgraeff** [comment]
All those topics are retained. The broker is not required to publish them in order. My openHAB implementation is order agnostic, I think that is the best approach.

**Comment by lorenwest** [comment]
Then the suggestion would be to remove references to any ordering from the spec? I think that's a good idea.

**Comment by boc-tothefuture** [comment]
@davidgraeff - good point on the topics not having to be sent by the broker in a defined order.

So it sounds to me like we are saying the documentation is wrong?  And that you do not have to send the $state topic with init as the first message as specified?  If so, I can open a PR to update that.

Is there a requirement that the you send a $state init before you send a $state ready?

**Comment by davidgraeff** [comment]
You would send the "init" if your device, nodes, properties take a bit of time to do their initialisation, I guess. Like if you need to read the structure from the network first or so. But like its done in the spec, it doesn't make much sense to me.

**Comment by boc-tothefuture** [comment]
@davidgraeff - Can I close this issue? I saw you tagged it as fixed in dev.  Wasn't sure if we kept these hanging until release so we had a change log/announce log.

**Comment by davidgraeff** [comment]
I just don't want anyone else to open a similar issue until the release happened.
