### ISSUE TITLE
Repository should only contain the convention

### ISSUE THREAD

**Issue by davidgraeff** [homieiot/convention#113]
With an upcoming website that contains sections like "FAQ", "Maintainership", "How to suggest changes", "Implementations" and so on I suggest to remove everything but the Convention itself from this repository. Even the TOC.

Everything else and new non-convention content would be added to the homepage repository.

**Comment by marvinroger** [comment]
So the `master` would only contain the latest built `README.md`? I mean, even the logo file could be hosted on the website, and referenced as an URL.

**Comment by davidgraeff** [comment]
I would say so. I made a first PR: #114
I just wonder how to redirect people from search engines and the github search to the website as main source for the convention. Maybe the very first sentence should mention the webpage? Alternatively the convention is moved to a different file and the readme.md tells the viewer about the purpose of this repository and the requirement for an MQTT convention and where to find the webpage.
