### ISSUE TITLE
Webpage "ID Format" links do not work

### ISSUE THREAD

**Issue by boc-tothefuture** [homieiot/convention#131]
None of the links that should go to the ID Format on the [spec page](https://homieiot.github.io/spec-core-v3_0_1/) work. They all link to https://homieiot.github.io/spec-core-v3_0_1/#topic-ids

**Comment by davidgraeff** [comment]
True. The website script does not embed the full specification document, because the introduction is not required. To unify the preface I have separated the https://homieiot.github.io/#mqtt-restrictions part and put it on the main page.

How do we proceed here?

**Comment by davidgraeff** [comment]
btw this issue is a webpage issue, please use the correct repository and issue board

**Comment by boc-tothefuture** [comment]
Closing and reopening in the appropriate repository.
