### ISSUE TITLE
Last will topic can only be set once per MQTT client/ represent a single Homie device

### ISSUE THREAD

**Issue by andig** [homieiot/convention#136]
This may be obvious, but I've only discovered it just now: using a single MQTT client for publishing multiple homie devices (or other non-homie use) is not possible since last will can only be set once and for a single topic as far as I understand. This seems to be an MQTT limitation.

Is it expected to use one MQTT client per published device? It seems like a waste of resources?

**Comment by davidgraeff** [comment]
It is a waste of resources, but Homie is limited by the capabilities of MQTT.

**Comment by bertmelis** [comment]
You should not confuse a Homie device with a real world device. One Homie device (hence one MQTT client) can connect as many real world devices as faisable.

I have a Homie "utilities" device (esp8266) which connectes my electricity meter, water meter and gas meter. They are just different nodes. It doesn't make sense to create multiple homie devices on one esp8266. Besides, should there be more then 1 Homie device on this esp, it is very likely that if one goes offline, the others will go offline too.

**Comment by davidgraeff** [comment]
A server software might expose multiple homie devices. A home device does NOT correspond 1:1 to physical devices.

**Comment by Thalhammer** [comment]
> A server software might expose multiple homie devices.

Yes that's true but in this case you have enough resources to open multiple clients, or if really don't want to do that, you can just ignore that they should be lwt topics and publish them the normal way.

**Comment by lorenwest** [comment]
I like to think of a `device` as the thing that has independent identity - a brain - usually consisting of a power supply and CPU - like an ESP8266, ESP32, Raspi, etc.

`Nodes` are things attached to the brain - LED outputs, buttons, sensors, etc.  All nodes within a device share the same lifecycle as the device, and only require a single MQTT will.

**Comment by andig** [comment]
> A server software might expose multiple homie devices. A home device does NOT correspond 1:1 to physical devices.

In my [case](https://github.com/gonium/gosdm630) gosdm connects multiple modbus meters (i.e. nodes) and each meter could physically disconnect. Since there is no node status I lose the ability to reflect that if I don't expose the meters as devices (which they really are).

> Yes that's true but in this case you have enough resources to open multiple clients, or if really don't want to do that, you can just ignore that they should be lwt topics and publish them the normal way.

Of course, but that violates the spec:

> lost: this is the state the device is in when the device has been “badly” disconnected. You must define this message as LWT.

**Update**

> Nodes are things attached to the brain - LED outputs, buttons, sensors, etc. All nodes within a device share the same lifecycle as the device, and only require a single MQTT will.

That would support the argument of "intelligent" meters not sharing the lifecycle of the server they are connected to?

**Comment by lorenwest** [comment]
In my view, anything with independent identity is a device with a name on the network. @andig, if the meter is intelligent - has a brain with a different MQTT connection as the server it's connected to, it's a device.

**Comment by Thalhammer** [comment]
You can add an online status to your nodes if you want. The spec does not prohibit adding custom attributes.

Multiple devices on a single connection will most likely never get supported (at least not until the mqtt spec allows for mutliple lwt's).

**Comment by fermuch** [comment]
> > A server software might expose multiple homie devices. A home device does NOT correspond 1:1 to physical devices.

> In my case gosdm connects multiple modbus meters (i.e. nodes) and each meter could physically disconnect. Since there is no node status I lose the ability to reflect that if I don't expose the meters as devices (which they really are).

You can add a `status` property to each of your nodes to set the connection state.

That way, you can know if your real device is alive (your host, the board that reads from the meters), and a separate state for each board, and determine if what is dead is your main board or a sensor board.

**Comment by davidgraeff** [comment]
Ok guys, I still like to point it out in the spec, that per "Homie device" a dedicated MQTT connection is required. Please help me with the pull request.

**Comment by davidgraeff** [comment]
@andig Why not remove the device node as soon as the modbus meter disconnects? Homie controllers need to be prepared for a dynamically changing node layout.

**Comment by lorenwest** [comment]
> Homie controllers need to be prepared for a dynamically changing node layout.

Really? Why does Homie attempt to define a device $type if you can't rely on devices of that type having a consistent node structure? What else would $type be used for?

I could see a particular node having a connected attribute, but I wouldn't like to see a device have dynamic nodes (beyond array-type nodes).

As a Homie implementor, I don't want to dynamically change the structure of a device over time. I grab the device structure when it comes online. 

Am I supposed to listen for changes to device definitions?

**Comment by davidgraeff** [comment]
@lorenwest It is implicitly written in the convention. The device $nodes attribute can be changed by the device at any time as well as the nodes $properties attribute can change at any time. 

It is not likely that it will happen, but a controller must be prepared.

The reasoning behind this is: MQTT doesn't guarantee an order and will not remove retained topics. So a device could disappear ($state=lost), restart, detect something new like new modbus components, comes online, sets $state=ready, sets the new device/$nodes value.
The controller will first see the old $nodes entry when the device comes online, then the new one.

**Comment by lorenwest** [comment]
@davidgraeff - Gotcha. Nodes and attributes are *generally* stable (cars don't just sprout engines), but devices do come in and out of service, and they could come back online with new versions containing new nodes/attributes. 

I see value in recognizing this relative stability, and possibly suggesting if nodes/attributes change, they should be accompanied by a different $fw/version, so a client can inspect the $fw/version and anticipate the car having an engine. Not all MQTT listeners are general purpose controllers - for those use-case specific clients, relying on a car having an engine is a valuable thing.

**Comment by lorenwest** [comment]
related: it would be great to suggest devices use [semver](https://semver.org/) for the `$fw/version` value.

**Comment by ThomDietrich** [comment]
Good stuff 👍
