### ISSUE TITLE
Proposal for new datatype formats

### ISSUE THREAD

**Issue by hondzik** [homieiot/convention#156]
Hello,
it would be nice to have additional predefined formats for color datatype for rgbw and maybe hex variants #rgb and #rgbw. 
It would be also great to have possibility to define ">x",  "x<", "<=x" and ">=x" ganges or at least positive/negative format for number datatypes.

Thanks,
Honza

**Comment by davidgraeff** [comment]
> It would be also great to have possibility to define ">x", "x<", "<=x" and ">=x" ganges or at least positive/negative format for number datatypes.

There is the "1-100" syntax existing. I can imagine to have "1-x" / "x-100" so keeping the syntax but allowing "x" as placeholder to express ">=" and "<=".
