### ISSUE TITLE
Dynamic settable/readonly Properties

### ISSUE THREAD

**Issue by stritti** [homieiot/convention#162]
It is not clear from the specification whether it should be possible to set a property attribute dynamically so that it can be set or readonly.

Background: I want to support an "auto" mode and a "manual" mode. Depending on this, another property should be changeable ("manual" mode) or not ("auto" mode).

**Comment by davidgraeff** [comment]
You can at any time unpublish a property and republish a property.

Telling controllers that a property has updated attributes is not yet supported.
Actually not a bad idea.

**Comment by stritti** [comment]
Maybe could be discussed for v4.

I asked because Homie-ESP8266 supports just `.settable()` without parameters.

**Comment by mjcumming** [comment]
@stritti can this be closed?
