### ISSUE TITLE
WoT/TD specification

### ISSUE THREAD

**Issue by andig** [homieiot/convention#163]
Looks like homie and https://w3c.github.io/wot-thing-description/ have a lot in common in terms of describing devices. Wondering if this will have any impact on the future oh homie?

**Comment by davidgraeff** [comment]
Not yet. W3C WOT is very comprehensive. Homie does only specify entities, and communication structure in a best fit way for MQTT. It is best compared to Mozillas Web Things API (Http+Websockets).

Homie also tries to be json free. WOT heavily relies on a structured format (json as an example, but I think they also allow binary formats like bson etc).

Personally I think a pub/sub transport like MQTT is not the best fit for IoT devices. An IoT device will usually not "subscribe" to anything (that would be a security risk if any network participant could command IoT devices), it will mostly publish. A 1:1 device<-->controller connection often makes more sense.

But as long as MQTT is used in the DIY IoT sphere, Homie will be there.
