### ISSUE TITLE
Meaning of $state ready

### ISSUE THREAD

**Issue by ghost** [homieiot/convention#165]
Hi!

The wording of the $state ready right now mentions:  'and is ready to operate'.
I think that's still a bit ambiguous. I guess that's partly intentional, but I assume ready to operate would mean at a minimum also: The device subscribed to all relevant topics (mainly set's for its properties). Mayby also something along the lines of whatever sensers are operating have started and will now be publishing values?
It feels like it could be described a bit clearer :)

**Comment by davidgraeff** [comment]
Just open a PR with a suggestion :) "Read to operate" to my understanding means 
1) all Homie related topics published
2) Eventloop is free to process incoming mqtt packets.

**Comment by mjcumming** [comment]
ready state clarified in the convention
