### ISSUE TITLE
Float range in Convention wrong?

### ISSUE THREAD

**Issue by zocker1996** [homieiot/convention#167]
Section 2.2.3 of the convention states:
"Floats range from 2^-1074 to (2-2^-52)*2^1023"
Is this correct?
Neither of this numbers is negative, and 0 is not included in this intervall.
This leads me to think that either my interpretation of these mathematical expressions is wrong,
or that maybe the minus sign should not be part of the power in the first expression.

**Comment by davidgraeff** [comment]
You are right. Might make sense to under-specify in this case actually.

**Comment by zocker1996** [comment]
I'm currently implementing a homie library for dart and need the max and min value as constants. Could you write them down here?

**Comment by davidgraeff** [comment]
Use IEE754 min/max for 32bit precision (https://en.wikipedia.org/wiki/IEEE_754-1985). Afaik that's what we have settled on and all 32/64-bit cpu's and mcu's can handle.

**Comment by zocker1996** [comment]
Thanks! The library is now documented and released. 
It can be found here: https://pub.dev/packages/homie_dart
Would you consider listing it in the [implementations tab](https://homieiot.github.io/implementations/#libraries)?

**Comment by davidgraeff** [comment]
Looks great! Sure I can do that. The website a repo here on the homieiot "organisation" as well btw :)
