### ISSUE TITLE
Arrays - removed from dev yet still referenced

### ISSUE THREAD

**Issue by peterhoeg** [homieiot/convention#168]
Further to https://github.com/homieiot/convention/issues/90#issuecomment-485070883, the section on arrays has been removed but there are still references to arrays:

- https://github.com/homieiot/convention/blame/develop/convention.md#L17
- https://github.com/homieiot/convention/blame/develop/convention.md#L101

So are they in or out?

**Comment by davidgraeff** [comment]
Those references should be removed. I'm not sure about the underscore, if it should be reserved for future use. I'd say no. Homie can always just use the dollar sign for specific meanings.
