### ISSUE TITLE
How to define/propose an extension? Concret: openHab label extension

### ISSUE THREAD

**Issue by zocker1996** [homieiot/convention#170]
Is their a guide how to define an extension?
What is an extension allowed to do?

Let me give you a concete example:
I want to propose an extension, which allowes you to add openHab labels to nodes an properties. These labels can then automatically be processed by openHab and linked to the appropriate openHab items (for properties) / channel groups (for nodes). A simple way to add such labels would be to just create a new attribute "$openhab-label" for properties and nodes. For example:
homie/super-car/engine/temperature/$openhab-label

What steps should I take to make an extension convention, what kind of information do I need to write down, is there a template?

**Comment by davidgraeff** [comment]
This is a primer, so there is no template yet. I would expect $type definitions and predefined properties and attribute values in such an extension. Maybe you give it a go as a PR to this repo? (Separate document)

If possible, make it independent of openHAB and think about the problem space and what you actually want to archive.

**Comment by zocker1996** [comment]
I'll try to come up with an idea for a template and a general structure based on the original convention document.
