### ISSUE TITLE
Homie 4.0

### ISSUE THREAD

**Issue by EP-u-NW** [homieiot/convention#176]
All requirements to reach Homie 4.0 are done by now 😀

I'd like to start a discussion if everyone feels comfortabel with the content of the convention, and if so, ask to introduce the current develop version as Homie 4.0.

**Comment by bertmelis** [comment]
I'd like to move on.

leftover to implement: https://github.com/homieiot/convention/issues/167

**Comment by davidgraeff** [comment]
Ok then. Let's move into fixes-only mode and target a release date. I suggest the 15th of August (in one week). Urgent matters may delay the release of course.

**Comment by EP-u-NW** [comment]
Sounds great! I already almost finished with the 4.0 implementation for dart, including the legacy and meta extensions.

**Comment by bodiroga** [comment]
@ThomDietrich, I just want to ping you here as you are "back" and were one of the most important developers of Homie :wink:

**Comment by EP-u-NW** [comment]
I think we are ready to go 😀

**Comment by davidgraeff** [comment]
Done. Don't know if the website will pick that up automatically, if not I need to trigger a rebuild.

**Comment by ThomDietrich** [comment]
Hey guys! Yes I'm "back" but still slow in catching up, as you can see. @bodiroga thanks for thinking of me. I did not look at all changes but I'm sure you did a great job improving those details that we once identified as the painpoints of Homie. Congrats! 🎉 
I was btw very happy to find this page: https://homieiot.github.io/implementations
