### ISSUE TITLE
Homie convention node for Node-RED

### ISSUE THREAD

**Issue by Christian-Me** [homieiot/convention#184]
Don't know if this is the correct place (if not I`m sorry).

I just finished a node for Node-RED to interface over MQTT using the homie convention. I`m a big fan of your work and use the homie convetion now for all my ESP8266 devices.

https://flows.nodered.org/node/node-red-contrib-homie-convention

Discussion should take place here:
https://discourse.nodered.org/t/announce-node-red-contrib-homie-convention/16329

**Comment by davidgraeff** [comment]
Hey thanks for this awesome addition to the Homie universe.

It's not very visible here on Github just as an issue. Could you maybe make a PR on the website repo (https://github.com/homieiot/convention-website) and add your Node-Red (+ discussion link) to the library page? Cheers

**Comment by Christian-Me** [comment]
Just created the pull request ... hope I did it right ... still not used with git & github.
