### ISSUE TITLE
GPIO0 in use

### ISSUE THREAD

**Issue by nelfata** [homieiot/convention#188]
I need to use GPIO0 on the ESP8266 to control an LED, but for some reason this is not possible.
It seems that it is used internally. I tried calling Homie.disableLedFeedback() but that made the GPIOs to toggle periodically and performing OTA upgrades no longer worked.
Please advise. Thanks.

**Comment by lorenwest** [comment]
Here's a good article on [using GPIO0, 2, and 15 as outputs](https://www.forward.com.au/pfod/ESP8266/GPIOpins/index.html).

Bottom line: Either stay away from those GPIOs as outputs or understand the issues well.

**Comment by davidgraeff** [comment]
Hm. Wrong repo. This is for the Homie spec not the firmware.
