### ISSUE TITLE
Official Logo / Banner 

### ISSUE THREAD

**Issue by Christian-Me** [homieiot/convention#194]
Hello,
1st and again a big thank you for your work.
I currently wonder if there is an official homie logo?
If found the "h" and the "mqtt/homie" graphics.

![image](https://user-images.githubusercontent.com/15779507/73563427-96bf7b00-445d-11ea-94b2-7e25069d0baf.png)
![image](https://user-images.githubusercontent.com/15779507/73563409-8b6c4f80-445d-11ea-8bda-b76fef11dcef.png)

1. which one should be used to identify the homie convetion?
2. Are there any style guides how to use the logo correctly? i.e. color / b&w version / inverted ....
3. Should a "works with" logo be designed to label hard and software products on websites or hardware. currently a rectangular frame with a (square & color) logo and text "works with ..." are widely used.
4. Are vector versions available (svg / webfont / fa / material icons / ...)
5. What is the correct "wording"? [homie convention] or [mqtt homie] or ... 
6. should there always be a link to https://homieiot.github.io/ included?

I think it is important to indicate a homie compliant product in an consistent and recognizable way to promote the homie convention. If you search for mqtt logo you get a couple of different designs. Perhaps because the original (?) is not accepted and difficult to use and a little bit out of fashion with its gradients and mostly incompatible color scheme.

My (first) personal opinion:

I like the h" logo. And it could be used together with a [works with] sticker
I like the idea of naming mqtt in the "official" name to indicate the base protocol but [homie mqtt convention] is far to long and I do not now if there are any legal issues.

I'm not a logo designer nor a CI expert so I`m totally open but I think there should be a well defined professional outside representation.

And here is the origin of my question:

![image](https://user-images.githubusercontent.com/15779507/73566719-d50c6880-4464-11ea-8ad8-ea5aa97debb5.png)

Node-RED demand logos / icons to be white with transparent background. I used the logo color as background. The icon of the second node could be perhaps interpreted as "misuse" of the logo. It should indicate the $state of a device as ready or lost ....

**Comment by davidgraeff** [comment]
The "h" is the original logo and used in a lot of places. For the website a banner like logo was required and I have quickly put together the mqtt-homie black/white one. Anyone can make suggestions for an improved logo though.

There is no real product identity yet though to answer the rest of the questions.

**Comment by Christian-Me** [comment]
Thank you for the quick answer.

Until then is it possible to get a svg or other vector format of the h" logo?. The available bitmap version is quite small and rendered against a white background so the conversion to a white icon with transparency lost a bit of quality. Node-RED also supprots svg icons for better readability as the work-space is zoom-able.

**Comment by davidgraeff** [comment]
@marvinroger Do you know where you have created the homie "h" logo and can you provide us with an svg version?

**Comment by marvinroger** [comment]
@davidgraeff @Christian-Me Hi!
I made it with [Sketch](https://www.sketch.com/). I've lost some files unfortunately, but I'll try to find it and report back. 😉

**Comment by marvinroger** [comment]
GitHub does not support uploading `.svg` files in the comment, so there you go, in `.zip`:

[Homie logo.svg.zip](https://github.com/homieiot/convention/files/4215529/Homie.logo.svg.zip)

**Comment by Christian-Me** [comment]
Perfect, thank you!

**Comment by stritti** [comment]
I think it would be a good idea to store origin svg here: https://github.com/homieiot/convention-website/tree/master/static/img
What do you think @davidgraeff & @marvinroger?

**Comment by marvinroger** [comment]
I completely agree!

**Comment by stritti** [comment]
I added it: https://github.com/homieiot/convention-website/commit/663a2d6e00dda506ae0a06236b38daee14f62771

**Comment by marvinroger** [comment]
Thanks a lot @stritti!

**Comment by stritti** [comment]
My son (student in graphic design) created some improved logos, banners and badges for us. What do you think:
![Homie3](https://user-images.githubusercontent.com/184547/77552673-1d1f9880-6eb4-11ea-9142-3f53a100ebd9.png)

![Homie4](https://user-images.githubusercontent.com/184547/77552677-1e50c580-6eb4-11ea-8484-89beea1bcd12.png)

![Homie](https://user-images.githubusercontent.com/184547/77552681-1ee95c00-6eb4-11ea-91c3-c703d2401461.png)

![Homie2](https://user-images.githubusercontent.com/184547/77552682-1ee95c00-6eb4-11ea-9fb7-9ac9a4220394.png)

**Comment by marvinroger** [comment]
Oh! You can thank your son on our behalf. 😉

I like the idea, but I think it's a bit bulky, and I'm afraid it would not integrate well on, typically, projects READMEs.

I was thinking about something like this, lighter (inspired by Amazon Alexa / Google Assistant / Apple Homekit):

<img src="https://user-images.githubusercontent.com/990773/77564892-b5714980-6ec3-11ea-9d14-6e86b41c8901.png" width="230" height="90" alt="Works with Homie">

**Comment by Christian-Me** [comment]
Great! I think there is a good reason to be "inspired" by all the others.

The only comment I have is perhaps to consider the proportion of the rectangle. Imagine sometimes an of the shelf product will have 2 or more of these labels on there packaging or advertisement. If you add mqtt to it it will fit. You can use homie even without any homie compatible controller.

**Comment by marvinroger** [comment]
@Christian-Me I am not sure I understand what you mean. A product would have 2 or more labels, so you'd prefer if it was smaller? But adding "MQTT" to it would make it bigger?

<img src="https://user-images.githubusercontent.com/990773/77863391-580e2d00-7222-11ea-9b75-fbc62b63e6e6.png" width="294" height="90" alt="Works with MQTT Homie">

**Comment by Christian-Me** [comment]
What I mean are products like this:
![image](https://user-images.githubusercontent.com/15779507/77913947-69445180-7295-11ea-926a-ccab58e4caeb.png)
- It is only about the proportion width to height not actually the size. The Spacing (white space around logo and text looks perfect.
- Would be nice to see the homie icon appear sometimes in the future next to alexa/google/homekit and what not. So there is perhaps no need to re-flash with a home-brew firmware - even most of us will do from a security point of view. 
- To add MQTT signals that even if somebody don`t use homie he can use mqtt. Perhaps try "homie • mqtt" or "Homie • MQTT" or "MQTT • Homie" (But I think Homie should come first "sits on top of mqtt")
- and perhaps try "works with" a little bit lighter or "Homie • MQTT" darker.

**Comment by stritti** [comment]
IMHO I suggest to remove the "technical" part "MQTT". The logo of HomeKit does also say nothing about their technical layer. Homie is the brand ;) Focus on the Enduser, not the developer there.

**Comment by Christian-Me** [comment]
I would agree but who is the end user? Who is the Homie end user?
It is definitely not the same as for alexa, homekit and all the others. Homie isn’t there jet.
The Homie Audience is more technical advanced. The “word” MQTT will push some positive triggers. As I wrote before homie is useful even when you do not have a homie compatible controller/device.
This label in the best case should attract end users but mostly developers or bedroom coders to take a look. It could help to signal that homie is a mature protocol based on a mature transport layer.

**Comment by Christian-Me** [comment]
Sorry It seams that I accidentally closed this issue.?

**Comment by davidgraeff** [comment]
Would be nice to update the logo on the website soon

**Comment by Christian-Me** [comment]
Think we have to agree to „with or without MQTT“ 
I would vote for with MQTT - because MQTT is an essential part of homie not only as an transport layer but also as a logic/functional essential part.

„homie MQTT“ or „Homie MQTT“. I would choose the Capital H.

**Comment by ThomDietrich** [comment]
I suggest

> "Homie MQTT Convention"

with the "Convention" piece visually downplayed. The name includes everything: A proper distinguished name, the core technology and the type of product we are talking about: A convention.

@stritti interesting point you make about MQTT being not relevant to the end user. I'm undecided.

Whatever we decide on. We need to update all documents to reflect this change.

**Comment by Christian-Me** [comment]
Perhaps the word „convention“ in an expanded font as a underline.

But I have some doubts of the word „convention“ in general because it has many meanings (and similarities in other languages) and could be perhaps misunderstood.


https://en.m.wikipedia.org/wiki/Convention

English is not my mother tongue - so It’s not up to me to give a recommendation here.

**Comment by Thalhammer** [comment]
I dont think we should put Mqtt in the logo.
While it might be the only broker supported right now, there is nothing big in the convention that limits us to using MQTT. Homie should be usable in pretty much any publish/subscribe broker that supports retained messages and qos or something similar. I dont intend to support something else tomorrow, but I think we should increase a dependency thats not really a thing.

Appart from that:
* Every developer looking for Homie will know it uses Mqtt anyway.
* Every end user using products based on homie should not need to care.

**Comment by stritti** [comment]
That could be my arguments, @Thalhammer

**Comment by Christian-Me** [comment]
One thing might worth considering: Adding MQTT could be useful especially If there will be multiple transport protocols in the future. I believe that not all devices will support all protocols so adding the protocol could be useful.
Another thing: For users/developers who already know homie the logo might already enough information. Users who don‘t know homie but MQTT (many hobbyists do) could be attracted to homie by mentioning the protocol they already know (and can start using even without any special homie controller).

Or miss I something here.

**Comment by mjcumming** [comment]
MQTT is widely known and having that in the logo makes sense to me. I think it will attract more users that might otherwise pass over the convention.

**Comment by stritti** [comment]
please let us finalize and take @marvinroger 's proposal? 
There are always pros and cons.

**Comment by mjcumming** [comment]
@stritti agree, lets get this done!

Reading above, I think majority feel that MQTT should be included in the logo. However, you (or your son) are doing the work so I would guess it's your call.

**Comment by Thalhammer** [comment]
Since the majority wants to include MQTT and I am not extremly against it I agree.

**Comment by stritti** [comment]
Okay, @marvinroger i think we will take your proposal (https://github.com/homieiot/convention/issues/194#issuecomment-605716163) could you provide it in several formats: SVG, PNG and add it to the repro?

**Comment by marvinroger** [comment]
I am not sure where you'd like to put it (on the website, in this repo...) so here it is: [Banner.zip](https://github.com/homieiot/convention/files/4600718/Banner.zip) 😉

**Comment by Christian-Me** [comment]
@marvinroger could you please convert the text (font) into a path/vectors in the svg as the font you used (which BTW is very nice) is not a standard font, or embed the font if the license allow this.
Otherwise the banner could look like this:
![image](https://user-images.githubusercontent.com/15779507/81494818-ece95900-92ab-11ea-86bb-4efef86c2af5.png)
Thank you for contribution, will add it into my projects ASAP

**Comment by marvinroger** [comment]
Oh my bad! Fixed here: [Banner.zip](https://github.com/homieiot/convention/files/4605446/Banner.zip)

**Comment by stritti** [comment]
Created PR on subproject convention-website.
