### ISSUE TITLE
Clarification: Broadcast 

### ISSUE THREAD

**Issue by rezreal** [homieiot/convention#195]
I do not quite understand the broadcast topicId (`level` from the example).  
Is `homie/$broadcast/foo/bar` considered a valid broadcast topic?
I see the terms:
- ID format (in the Broadcast section, which references Topic ID)
- Topic ID
- topic level ID
- MQTT Topic  (which consists of multiple consecutive `topic level ID`s?)

Now I am a bit confused if a broadcast topic may have multiple levels :) At least the homie-esp8266 implementation does not support that, and I am wondering what the intention of the spec was.

**Comment by davidgraeff** [comment]
MQTT topic matching is mostly based on string matching on the client and server side. I do not see a point in restricting a broadcast topic to just one level, technically. So "homie/$broadcast/foo/bar" would be a fine topic. Any other opinions?

**Comment by mjcumming** [comment]
I agree. @Thalhammer ?

**Comment by Thalhammer** [comment]
I dont see any problem with supporting multilevel ids for broadcasts. However we should make sure all (or at least the reference) implementations correctly subscribe to homie/# instead of homie/+ before we change the comvention.

**Comment by mjcumming** [comment]
I don't use this feature and  I don't recall any conversations on the OpenHAB forum discussing it. The spec defines this as a controller broadcast. Do we allow devices to use this mechanism as well? I see more utility for this feature if we are able to develop some predefined device types. Ie. if there was a light device and a broadcast could turn all lights on/off.

**Comment by piegamesde** [comment]
> Ie. if there was a light device and a broadcast could turn all lights on/off.

Wouldn't this be the job of a home automation system?

**Comment by mjcumming** [comment]
> > Ie. if there was a light device and a broadcast could turn all lights on/off.
> 
> Wouldn't this be the job of a home automation system?

Yes, a controller could do this but in this instance rather than iterating over all homie light devices and sending separate set commands, a single broadcast would cover them.

**Comment by mjcumming** [comment]
clarified in https://github.com/homieiot/convention/commit/d68076d00e50b1b276e4eab52915961232050e8f

**Comment by rezreal** [comment]
awesome, thanks!
