### ISSUE TITLE
Stepping down as maintainer

### ISSUE THREAD

**Issue by davidgraeff** [homieiot/convention#199]
Hey guys,

as we lack a "community" communication channel, I'll abuse the Github issue system for this announcement and will remove the issue in two weeks from now again.

I'm stepping down as Homie maintainer.

Please do not wait for a response of mine in ongoing discussions and open issues, and just continue without my acknowledgement. 

My reasons are not so much to be found in personal or live changing events.

I just do not see MQTT as the right underlying protocol for (DIY) IoT (smarthome) devices. 
Don't get me wrong. Homie is a necessary project. For all those people that insist on using MQTT, it's good to have a common denominator.

Thanks all and stay healthy,
David

**Comment by mjcumming** [comment]
Does that leave any active maintainers? Is there a plan to replace you?

**Comment by davidgraeff** [comment]
> Does that leave any active maintainers? Is there a plan to replace you?

For OH there are some new people contributing to the MQTT addons. For the convention itself, there is no replacement. According to the website @Thalhammer is still an active maintainer, maybe he can comment on this matter?

**Comment by peterhoeg** [comment]
Just out of curiosity (and this may very well be the wrong place for this discussion), what do you as the *right* protocol if mqtt is not it?

And thanks for all your hard work!

**Comment by davidgraeff** [comment]
If you look through the issues you will note a few shortcomings of mqtt yourself. It's mostly about only having a string data type and no support for structured data. That's why a "competing" convention uses JSON for topic values, which is IMO just fighting the symptoms.

Something like CoAP could do (UDP, dtls). There are many projects layering on top of that protocol already with huge registries for predefined smarthome appliances. I'm personally using it. Or a simple http rest API like the Mozilla WebThings API.

**Comment by mjcumming** [comment]
I haven't seen a post from @Thalhammer since April 2019. Perhaps @davidgraeff can appoint someone to take his place so the project continues.

**Comment by Thalhammer** [comment]
I am still here but even though I am listed on the website as a maintainer, I am not. I never got any rights to do anything here in the repo (i.e. no merges or managing issues). Also I had some own projects which took some of my time.
I would be happy to take over as a maintainer if there is interest in it. I did not have lots of spare time in quite a while but that should get better in the next time.

**Comment by Thalhammer** [comment]
That said I kind of agree with @davidgraeff that MQTT has some problems which are hard to solve with a simple convention based on top of it.
This includes, but is not  limited to:
* No guaranteed ordering of messages
* No datatypes
* No synchronous operations

These are just a few that came to my mind. Some are solvable (like the datatypes), some are not (message ordering) which makes implementing the management side kind of a mess if you want to do it right.

Also there are some things about the convention itself which I dislike:
One example would be putting management info into multiple topics (e.g. listing nodes and properties in topics). While on paper it looks elegant, it makes a proper server/client implementation pretty hard. A single topic with some sort of json descriptor would have been better, but I know why @davidgraeff did not want to make json support a requirement.

**Comment by mjcumming** [comment]
@davidgraeff would you give access to the repository to @Thalhammer ?

**Comment by davidgraeff** [comment]
I thought @Thalhammer has full access already, sorry for that.
I will also add you, @mjcumming.

**Comment by Thalhammer** [comment]
@davidgraeff Nope that somehow was forgotten when we discussed maintainership back than and since I had enough other work I did not really care tbh.

**Comment by piegamesde** [comment]
IIRC, @davidgraeff you were the only maintainer of the OpenHAB plugin? Does it mean that it is orphaned now?

**Comment by davidgraeff** [comment]
14 days are over, closing this issue now.

The openhab mqtt add-on is very modular. Only the homie part is orphaned, but I have seen new committers already.
