### ISSUE TITLE
The documented specification shows an invalid example for Device Attributes

### ISSUE THREAD

**Issue by cmoore42** [homieiot/convention#203]
Section 7.1.1 in the spec says, "The following device attributes are mandatory and MUST be send, even if it is just an empty string".  It then lists the mandatory Device attributes:  $homie, $name, $state, $nodes, and $extensions.

This is followed by an example for a "super-car".  However, that example does not contain a $extensions topic, which the specification says is mandatory.

**Comment by cmoore42** [comment]
I've noticed something else in this example that appears to be invalid.  The homie/super-car/$nodes example sets that attribute to "wheels,engine,lights[]".  It is not specifically called out, but I believe these values are supposed to be the ID of the nodes that are supported.  "lights[]" is not a valid ID according to section 2.1.

**Comment by mjcumming** [comment]
fixed the example for $extensions. I cannot find the "lights[]" reference. That was part of the convention prior to v4

**Comment by Thalhammer** [comment]
lights[] used to be a valid id and represented an array which got removed in v4. So its possible the examples where missed during updating.

**Comment by mjcumming** [comment]
I looked and didn't find any. @cmoore42  if you could point to where the "lights []" reference is I'll fix.

**Comment by cmoore42** [comment]
Homie specification online at https://homieiot.github.io/specification/

Section 7.1.1.

At the end of the section, just before 7.1.2, the following example is given:

homie/super-car/$homie → "2.1.0"

homie/super-car/$name → "Super car"

homie/super-car/$nodes → "wheels,engine,lights[]"

homie/super-car/$implementation → "esp8266"

homie/super-car/$state → "ready"

 

The value for the $nodes attribute is not valid under this version of the spec.

**Comment by mjcumming** [comment]
@Thalhammer not sure how to fix this, the convention.md file has been fixed but those changes have not propagated to the homie website.

**Comment by Thalhammer** [comment]
Looks like the website is updated by travis and in fact if you look [here](https://homieiot.github.io/specification/spec-core-develop/), it has.
If we would like to have the v4.0.0 version (the default if you click on the spec link) to change, I assume we would need to change the tag to a version that includes the changes.

But we cant simply do that as the master branch already includes other changes that should not be included in 4.0.0.
My idea would be to make a branch per version for stuff like typo and grammar fixes. Since they dont really change the spec, I also dont think they should affect the version number.

**Comment by mjcumming** [comment]
@Thalhammer agree, we need to a process to manage typo/verbiage issues and protocol changes. Happy to do that any way you want.

**Comment by daenney** [comment]
I just ran into this snafoo too. I was trying to figure out what this `lights[]` thing was about until I stumbled on this issue. I would be nice if typo/verbiage fixes could make it to the naked https://homieiot.github.io/specification/ and versioned https://homieiot.github.io/specification/spec-core-v4_0_0/ locations

**Comment by Hypfer** [comment]
This apparently was already fixed in 12453d851b85783dd5323430ce3aa85fcc376641 in 2019.

Unfortunately, that hasn't been deployed yet it seems

**Comment by mjcumming** [comment]
I don’t see a formal pull request for the change
________________________________

**Comment by daenney** [comment]
@mjcumming The PR for it was #177. The change is there, it's just not deployed properly everywhere.

**Comment by Tieske** [comment]
afaict the change were deployed. So closing this.

please reopen if something is still missing.
