### ISSUE TITLE
Minor typo which causes link to anchor/id to fail

### ISSUE THREAD

**Issue by clmcavaney** [homieiot/convention#204]
G'day,
I discovered a minor typo that is causing a link to an anchor to fail.

In the table below this heading:
https://github.com/homieiot/convention/blob/develop/convention.md#property-attributes
There is a link to "#payloads" (with link text "Payloads") in the $datatype row, it should be "#payload".

I haven't worked with a .github.io repo before, so not entirely sure how to reference the line in this issue.  So, I hope the link above is useful.

Regards,
Christopher

**Comment by mjcumming** [comment]
Fixed!
