### ISSUE TITLE
Datatype for duration is not clear

### ISSUE THREAD

**Issue by rhierlmeier** [homieiot/convention#206]
I think specficiation does not clearly define what datatype a property with duration payload has.
Is the datatype string?

```
homie / device123 / mythermostat / open-duration→ PT10s
homie / device123 / mythermostat / open-duration/ $name → Open duration
homie / device123 / mythermostat / open-duration/ $unit → duration
homie / device123 / mythermostat / open-duration/ $datatype → string
homie / device123 / mythermostat / open-duration/ $settable → true
```

**Comment by Thalhammer** [comment]
https://github.com/homieiot/convention/blob/develop/convention.md#duration

Datatype should be "duration" and unit (which is optional) should not be present.

**Comment by mjcumming** [comment]
all messages are sent using payloads as strings
