### ISSUE TITLE
Spam from "Amirosein Abbasi"?

### ISSUE THREAD

**Issue by stefan-muc** [homieiot/convention#211]
Just asking, did some people here also get a Mail from a person pretending to be "Amirosein Abbasi" with a question to participate in a survey about IoT systems (as I am a person that contributed here)?

I got one today 12:14 UTC+2 to a mail address I used as Git mail address in some other project I host on Github and consider this as spam.

**Comment by Thalhammer** [comment]
I don't think I did. And if I did I probably deleted it on sight.

That said: how is this related to this project (As in whats the issue here) ?
