### ISSUE TITLE
Difference between OCF/Iotivity/WebThing API & Homie

### ISSUE THREAD

**Issue by echo1consulting** [homieiot/convention#22]
Hello, are you familiar with [OCF](https://openconnectivity.org/) and [Iotivity](https://www.iotivity.org/)?

It seems that there are similarities in the mission of Homie and OCF.

**Comment by marvinroger** [comment]
Hi!

I don't, but yes, the end goal is the same: try to "standardize" how IoT devices work. But if you know more about OCF and Iotivity and given the fact that Homie is a rather short document, maybe you are in the best position to explain what are the differences. 😉

**Comment by davidgraeff** [comment]
Should this be mentioned on the website somewhere? There is also https://iot.mozilla.org/wot/ as a 3rd alternative spec.

**Comment by marvinroger** [comment]
I’m for openness, so yes. It might even help for Homie adoption, as people would be able to quickly compare the alternatives.

**Comment by davidgraeff** [comment]
@marvinroger Could you use https://github-issue-mover.appspot.com/ or similar to move this Issue to the webpage repo?

**Comment by marvinroger** [comment]
This issue was moved to homieiot/convention-website#2
