### ISSUE TITLE
Matrix room for project chat

### ISSUE THREAD

**Issue by colemickens** [homieiot/convention#226]
Hi. I've recently discovered Homie and it looks quite exciting. I have some thoughts/questions about it and was wondering if there's a discord/matrix room for discussions.

Can I suggest a Matrix room somewhere?

Thanks!

**Comment by euphi** [comment]
There is a gitter-Chat that is also connected to Matrix: https://matrix.to/#/#homie-iot_ESP8266:gitter.im?utm_source=gitter
