### ISSUE TITLE
How can I create a settable property, which takes two arguments?

### ISSUE THREAD

**Issue by rzarajczyk** [homieiot/convention#227]
Hi
How can I create a settable property, which takes two arguments? The example would be a Philips Hue light, which can have a property `brightness` - I can set it to a different value, but I can also specify the `transition time`. Transition time may is an optional parameter, but also important - how should Homie Convention property look like to support such use cases?

**Comment by Tieske** [comment]
That doesn't fit Homie. Homie is about "state", what you want is more about RPC.

If anything, the device should get 2 properties;
- brightness
- transition time

Then you first set transition time, and after set brightness

**Comment by rzarajczyk** [comment]
Ok, thank you!
