### ISSUE TITLE
Representing a state machine

### ISSUE THREAD

**Issue by nstadigs** [homieiot/convention#305]
i have a controller that uses state machines and I was hoping to be able to represent them using the homie convention.

Here's a simple example:

![mermaid-diagram-2024-11-01-095617](https://github.com/user-attachments/assets/8b0b698e-0948-422f-9163-93d221d68d34)

This machines has two states (Paused, Running) and two transitions/actions (start, stop).

My initial intuition was to represent these as enums, where the payload can be Paused or Running and the /set endpoint listens for "start" and "stop" payloads. But it's not clear to me what the $format property represents in this case. It should probably be the payloads accepted by the /set endpoint, right?

How would you represent this using the homie spec?

**Comment by nstadigs** [comment]
Found #70 and realized that I should probably represent the machine as a node and the states and actions as two different properties:

/homie/5/controller/my_machine/states <-- enum, not settable
/homie/5/controller/my_machine/actions <-- enum, stateless, settable

**Comment by nstadigs** [comment]
(would it not be nice to activate the "Discussions" feature in this repo?)

**Comment by Tieske** [comment]
> My initial intuition was to represent these as enums, where the payload can be Paused or Running and the /set endpoint listens for "start" and "stop" payloads. But it's not clear to me what the $format property represents in this case. It should probably be the payloads accepted by the /set endpoint, right?

If using state, then the `/set` topic will accept the state values, so "running" or "paused" in this case. If the response is immediate then this would work.

**Comment by Tieske** [comment]
Here's how I solved a similar issue: https://github.com/Tieske/homie-mertik-maxitrol/blob/47662ff7047e29b39a7b0c3a053c3969824812d6/homie-mertik-maxitrol.ino#L846-L880

A fireplace that takes a while to respond, when igniting/extinguishing (up to a minute). So the pilot flame is a boolean, that is settable. There is a second property "status" that reports the in-between states. Note that the boolean in this case uses a `$target` attribute to indicate that it is working towards a new state.

**Comment by nstadigs** [comment]
Thanks for the tips! I'm making a thing that publishes [xstate](https://stately.ai/docs/xstate) actors as homie nodes and I think that I have something that works following the pattern above. I believe your example validated my approach :pray:
