### ISSUE TITLE
Enable the "discussions" feature?

### ISSUE THREAD

**Issue by nstadigs** [homieiot/convention#307]
I don't know if this community already has a forum for discussions somewhere, but I haven't seen one.

Maybe you could enable the discussions feature in this repo? People could use that space to discuss implementations, ask questions, announce new devices and libraries, etc. This convention repo seems like a good central space for these things.

What do you think?

**Comment by Tieske** [comment]
There's a Matrix channel: https://matrix.to/#/#homie-iot_convention:gitter.im

**Comment by Tieske** [comment]
But we could also enable discussions here. Wdyt @schaze @Thalhammer ?

**Comment by jacoscaz** [comment]
I also feel that enabling discussions here on GitHub would be a good idea. Communities are somewhat fragmented across multiple services (Matrix, Discord, ...) but GitHub is a reliable constant and offers decent tooling for notification management.

**Comment by Thalhammer** [comment]
Matrix, while existing, isn't really used by a lot of people (heck even I don't check it regularly).
I think github discussions might be a good bit more accessible for most people.

**Comment by Thalhammer** [comment]
I enabled it with the standard setup recommended by github, but we can modify that if needed.
