### ISSUE TITLE
Improvement to Documentation

### ISSUE THREAD

**Issue by thetonto** [homieiot/convention#41]
Been working with Homie a couple of days now.  Small stumble was what the topics were.  Suggest the following

devices/686f6d6965/temperature/temperature → 12.07
devices/686f6d6965/humidity/humidity → 79

become

devices/686f6d6965/temperatureNode/temperature → 12.07
devices/686f6d6965/humidityNode/humidity → 79

Got it all working and very impressed!

**Comment by euphi** [comment]
You are right, this is confusing.

The document is redesigned right now, see https://github.com/marvinroger/homie/tree/redesign .
The current revision already distinguishes better between Nodes and their properties.

**Comment by ThomDietrich** [comment]
@thetonto exactly what @euphi said. The documentation will be clearer soon.

Just to address your improvement: I don't know about your specific use case but in general the nodes should receive "node-like" names, the properties should receive "property-like" names. I believe the new document makes that clear.

So instead of:
```java
devices/686f6d6965/temperatureNode/temperature → 12.07
devices/686f6d6965/humidityNode/humidity → 79
```
You should aim for something similar to
```java
devices/my-weather-station/outdoor-probe/temperature → 12.07
devices/my-weather-station/outdoor-probe/humidity → 79
```
or
```java
devices/my-weather-station/thermometer/measurement → 12.07
devices/my-weather-station/hygrometer/measurement → 79
```

**Comment by euphi** [comment]
@ThomDietrich  I think @thetonto  had a look at the "master" tree of the Convention, which is the old 1.0 version. This version used "devices" as default base topic.

**Comment by ThomDietrich** [comment]
Ah I see. @marvinroger a [better branching structure](http://nvie.com/posts/a-successful-git-branching-model/) would maybe solve that?

**Comment by marvinroger** [comment]
Well, I badly managed the versioning. To be honest, I did not expect the Homie Convention to become that successful (and I'm glad it did). Things should stabilize when we consider this "2.1.0" as final, we will merge that "redesign" branch into "v2" that will get merged to "master". "master" will always contain the stable Convention, and releases will be tagged following semver. So it won't be a problems anymore. :wink:

**Comment by marvinroger** [comment]
About to be released with the new `super-car` device example. Expect 2.1.0 soon (promise) 😄

**Comment by ThomDietrich** [comment]
@marvinroger I'm still not convinced that the super-car is a good example 🙊

**Comment by marvinroger** [comment]
Oh? I missed that part. 😅
Do you have an idea for a super-good example?

**Comment by davidgraeff** [comment]
The original problem is solved, I guess? Please reopen otherwise :)
