### ISSUE TITLE
Range batch set

### ISSUE THREAD

**Issue by Thalhammer** [homieiot/convention#49]
Currently, if you define a range property you get a subtopic for every range item which is fine.
However, if you have a lot of items its get quite a lot of work and traffic to set them all.
In my opinion, it would be a good thing if one could set them all with one message.
Assume this setup:
```
homie/ledstrip-device/ledstrip/$type → ledstrip
homie/ledstrip-device/ledstrip/$properties → led[1-3]
```
Doing this:
```
homie/ledstrip-device/ledstrip/led → on
```
Should be equivalent to this:
```
homie/ledstrip-device/ledstrip/led_1 → on
homie/ledstrip-device/ledstrip/led_2 → on
homie/ledstrip-device/ledstrip/led_3 → on
```

Regarding the format of messages published to this batch topic I suggest the following:
```
<value>
```
=> Set all items to value
```
1-2:<value>
```
=> Set items 1 and 2 to value, don't modify item 3
```
1-2:<value>
3:<value2>
```
=> Set items 1 and 2 to value and item 3 to value2

**Comment by marvinroger** [comment]
Check the [redesign](https://github.com/marvinroger/homie/tree/redesign) branch, *range properties* doesn't exist anymore. Instead, it's replaced by `node arrays`, which makes more sense. Anyway, we have to freeze features for now, to move forward. Let's keep this in mind for a potential future update. 😉

**Comment by Thalhammer** [comment]
Sorry for the late reply.
Thanks for pointing out the redesign branch, indeed I did not see it.
However, the "problem" applies to node arrays as well.
I understand your intent to freeze features and will keep it in mind for version 3.1.0 ;-)

**Comment by davidgraeff** [comment]
Closing in favour of the discussion in #90.
