### ISSUE TITLE
Setting device interval value

### ISSUE THREAD

**Issue by tripflex** [homieiot/convention#54]
Forgive me if this is possible and I haven't figured it out yet .... but is there not any way to SET the interval value for the device?  As in to configure how often to send the stats?  I guess I just assumed this was possible, as I don't see what the interval config is even really for if it's not settable ... ? 

Reason being ... use case scenario would be outputting data on a dashboard ... so when the user is viewing dashboard for a device, we would want to update the interval to say, every 15 seconds to give a better UI experience, whereas, when just storing stats, we would only want it set to every 300 seconds (5 minutes) instead 

Am I missing something here?

**Comment by ThomDietrich** [comment]
Hello, please join #53

**Comment by davidgraeff** [comment]
Closing in favor of #53.
