### ISSUE TITLE
More flexible Node configuration

### ISSUE THREAD

**Issue by euphi** [homieiot/convention#57]
There's a  discussion in https://github.com/marvinroger/homie-esp8266/issues/467 about how to be more flexible in Node configuration.

As this is not the implementation-specific but belongs to the convention, I opened a new issue here.

As far as I understood the proposal of @ingoogni, nodes should be independent from devices (e.g. a node can be distributed over several devices).

I still think this proposal is beyond "lightweight", but it may be ok if you somehow define "virtual" nodes that can be distributed over several devices.

**Comment by ingoogni** [comment]
To elaborate a bit more:

semantic topic strings (versus device oriented topic strings)

device = ESP-Homie or more general Homie-MQTT-client (with sensors and/or actuators etc.)

In the semantic view processes, locations, situations etc. are independent of the devices that publish or listen on them. The device it self is an entity within the semantic view.

root/trunk/branch/leaf (Homie: root/device/node/property)

- In a semantic view we can have multiple topics with different roots, trunks etc. published from one device.

- We can also have multiple devices publishing to the same root/trunk/branch and even leaf.

Both are not possible with the current convention.

In this semantic view the relation between the publishing device and the process or room etc. can be maintained by publishing metadata from the device on what semantic topics it publishes. (the $ signs for metadata are so nice)
```
.../device/.../$publishes => ["self", ".../.../..", ".../.../.../.."]
```
Although normaly a proces or location doesn't know who or what publishes about it, if we know we could add this metadata also to the semantic topic. 
```
.../room/light/brigtness
.../room/light/brightness/$publishedby => ".../device/..."
```
It would require some manual set up where as the $publishes on the device topic above could be auto generated even when topics are dynamicaly generated.

In such a general set up it would be relative easy to build a device oriented setup as Homie now is. Getting a complete semantic set up from current Homie requires filtering and probably even rewriting topics by the broker.


Going through the convention, backwards. Property attributes (leaf attributes) would not change. Node attributes would not change. Device attributes (trunk attributes) would change to some extent in that the 'trunk' where the device lives has quite some (network specific) attributes that are not needed in other 'trunk's'. But for example the attribute $online can be usefull for more than one thrunk or node (one of two sensors is defect).

**Comment by ingoogni** [comment]
ref #101 

````

        +-----------------------------+
+-------| Homie Core                  |======= can be service provider
|       + . . . . . . .+--------------+        of multiple namespaces (devices)
|       | Homie Device | Light Device |=======+
|       +  Nodes       |  Nodes       +       |
|       +   Properties |   Properties +       |
|       +--------------|--------------|       |
|           |          | Pressure Dev +       |
|           |          |  Nodes       +     +=========
Base        |          |   Properties +     | Namespace can span 
topic       |          +--------------+     | multiple devices
|           |                               | /livingroomlights
|           |                               +==========
|         Distinct                            |
|         namespaces                          |
|           |                                 |
|           |                                 |
|       +-----------------------------+       |
+-------| Homie Core                  |       |
        + . . . . . . .+--------------+       |
        | Homie Device | Light Device |=======+
        +  Nodes       |  Nodes       +
        +   Properties |   Properties +
        +--------------+--------------+
````
Devices: An instance of a physical piece of hardware is called a device. For example, a car, an Arduino/ESP8266 or a coffee machine.

Devices: An instance of a physical piece of hardware or software, serviced by Homie (Core?) is called a device. For example, a sensor (array), a time server, a car, an Arduino/ESP8266 or a coffee machine.

**Comment by davidgraeff** [comment]
@ingoogni Actually you are defining a very own convention "Semantic View 1.0" on MQTT. It doesn't have anything in common with the device/node/property specific Homie convention ^^. You just like the way that nodes and properties have their defined attributes, but you can just copy those parts over to your convention.

**Comment by ingoogni** [comment]
It just decouples the HomieCoreDevice from the 'devices' it services. In the current convention the coupling is "hardwired" and implicitly requires that there will be only one device, the intergrated one. While our hardware is more than capable enough to run multiple 'devices'.

Practically it means I should buy more hardware. Practically it may also mean that if someone decides that the ESP implementation should follow the convention strictly many projects can be put in the bin (my guess).
Another practical one, for fun I have attached a HBMQTT client to the bus of Cherrypy pushing MQTT data to the webserver and POSTed data to the MQTT broker. That client could run following the convention, but also following the convention I should run multiple clients while serving different 'namespaces'...

If decoupled, every other bit of the convention still stands, so certainly not my convention. Device oriented implementations will still work.

**Comment by davidgraeff** [comment]
A hardware device can propagate multiple homie devices. You really want something different not related to this convention.

**Comment by ingoogni** [comment]
Educate me. So far no one has done. It could become a great piece of documentation.

**Comment by davidgraeff** [comment]
Apparently you are referring to the esp8266 homie implementation? Open a bug there if the firmware does not allow you to create multiple class instances with a virtual homie device each. Has nothing to do with the convention. The word device could also have been service. But it doesn't matter really

**Comment by davidgraeff** [comment]
Closing this as being a suggestion to change the convention entirely to a different model. Please reopen if I have overlooked a detail that can be used in the convention as it is.
