### ISSUE TITLE
Homie Convention v3.1

### ISSUE THREAD

**Issue by timpur** [homieiot/convention#61]
## Tasks for release of v3.0.
[ ] Clean up branches
[ ] Talk about final additions for v3.0
[ ] Review and clean up formatting.

Anything else? Lets talk.

@ThomDietrich @bodiroga @bertmelis @ingoogni @euphi  @marvinroger

**Comment by timpur** [comment]
Also there was talk in homie-esp8266 if stats should be implemented as a node and follow the node format. This would make properties and stats discoverable with units ect....

**Comment by euphi** [comment]
Yes, $stats as a specialized form of a regular node seems very useful to me.
