### ISSUE TITLE
What is defined as an announcement?

### ISSUE THREAD

**Issue by nerdfirefighter** [homieiot/convention#65]
Can we define which topics are considered announcements in the documentation?

This would be useful to understand what topics would be defined by the time the device state turns to ready.

My understanding is that when the state goes to ready, every node is defined along with all the properties to the level that we know what all the topics are.

**Comment by timpur** [comment]
TBH that's also my assumption.

Any reason this shouldn't be the case. I believe all discovery messages should be sent before ready is set. Some messages will come after, like stats. But yes I might go through them and marks the ones defined latter after ready or something like that.

**Comment by euphi** [comment]
I tagged this as "bug", because the convention is not clear enough regarding this.
(However, we already defined the various states in the new convention a, so it is not an enhancement).

**Comment by ThomDietrich** [comment]
Imho this is related to #51
