### ISSUE TITLE
V2.0.1 Small Add for Discovery ... $nodes

### ISSUE THREAD

**Issue by timpur** [homieiot/convention#68]
In my pursuit to make a Homie Addon for Home Assistant, ive discovered that not having `$nodes` like $properties make a huge difference in how you discover nodes... So i propose a small change to add this to v2 as v2.0.1

Its also such an easy thing for implementations to implement so i see no reason not to. I know v3.0.0 has but thats a whole redesign and breaking changes to implement and will take time...

@marvinroger  @ThomDietrich

**Comment by euphi** [comment]
I agree. It is an addition, so it does not break compatibility.

**Comment by euphi** [comment]
Oh, btw, the titte is v2.0.0.1, but I think it should be v2.0.1 (as mentioned in your comment).

**Comment by timpur** [comment]
Typo...

**Comment by marvinroger** [comment]
I agree too, if it makes things easier.

**Comment by timpur** [comment]
I'll make a PR tomorrow then :)

**Comment by ThomDietrich** [comment]
@timpur which commit will this PR be based on? The one tagged as v2.0.0?

**Comment by timpur** [comment]
Yes

**Comment by ThomDietrich** [comment]
Sounds okay to me. Are you okay to wait till we sorted out #46 and #69 ? Seems like we will come to an understanding today.

**Comment by timpur** [comment]
@ThomDietrich, still confused on what im meant to do with this, can you just give me instructions. More confused about what to do with the branch after release and tagged ...... i thought we wanted to delete branches and only have master.

**Comment by ThomDietrich** [comment]
I've done you one better, here you go: https://github.com/marvinroger/homie/tree/release-v2.0.x
Feel free to commit changes into this branch as you see fit.

You are mixing topics. Of course we are still using branches. Just no constant develop branch as it is common for big software projects. Every iteration (i.e. improvement or addition) will be nurtured in a Pull Request and merged as soon as it is ready to be part of the convention in the master branch. Think of every PR as one of many small develop branches.
Now the topic of improving an older version of the convention is unrelated to the advancement of the master branch. You are thinking about taking an older state of the convention and adding a new detail. If you want to do that you need a new "workspace" for that, outside the advancements towards and beyond v3.0.0. That's what a branch created from the "v.2.0.0" tag is for. You are now able to add unrelated changes in this workspace unhinged from the master branch, in the end we will mark this branch with the "v2.0.1" version tag and voilà, your addition will be available to users alongside other version tags.

I hope that helped ;)

**Comment by timpur** [comment]
You didn't finish with what to do with with the branch after tagging. Do you just delete the branch and it should magically remain because of the tag ? You guys fail to explain this last part which I've asked acouple of times now ....

**Comment by ThomDietrich** [comment]
Nothing. At least not necessarily. The fact that a tag will point to the head of the branch allows us to delete the branch (and potentially recreate it later). This is something we can do either way @euphi wdyt?

I'm sorry that my excessive explanations did fail your expectations. You could always... you know... do some research on the matter. https://stackoverflow.com/questions/1307114/how-can-i-archive-git-branches

**Comment by timpur** [comment]
Haha sorry, long day. Didn't mean to come across as rude, but damm ripped. I'll just rip now.

**Comment by timpur** [comment]
@ThomDietrich, anything else i need to do ? 
https://github.com/homieiot/convention/releases/tag/v2.0.1

**Comment by ThomDietrich** [comment]
Yes looks good. 👌
Now that you've also pushed the nodejs implementation, I'd say you should delete he tag and move it one commit forward.

**Comment by timpur** [comment]
True that. Not very on the ball aim i.
