### ISSUE TITLE
new Datatype map? (Or use different formats for enum)? 

### ISSUE THREAD

**Issue by euphi** [homieiot/convention#72]
In case you have a node property of type enumeration, but this enumeration has many elements, it can be useful to still use integer values for MQTT communication. However, also in these cases you want to announce the possible values with their meaning.

The current 3.0 convention allows to announce enumerations with their possible allowed values, but no mapping of integer values to a meaning.

As an example, in my [ESP_Homie_WS2812FX](https://github.com/euphi/ESP_Homie_WS2812FX) Node there is a "mode" property that allows all modes from the WS2812FX lib. However, when setting a new mode, I still want to receive the new mode as integer, because it is much easier to parse.

So, for the announcement there should be a way to announce the mapping of the integer to it's corresponding mode name, e.g `46: Fire Flicker, 47: Fire Flicker (soft)` etc.

What is your opinion about this?

- Don't use integer, when you want something else, so send a string with the mode's name.
- Lets extend the enum "format", so you can give each allowed enumeration value a description string.
- Add a new dataype `map` that maps allowed integer values to a string.

**Comment by davidgraeff** [comment]
The description is just for the controller for a prettier view. Therefore I suggest to separate the integer enum and the description into their own topics each and using a more generic approach by having a new attribute. 

I propose "vdescription" / "value-description" / "value_description" that is so far only defined for an enum type, but could in theory also make sense for a boolean value for example. "true" often means "On" etc.

The "vdescription" would contain a comma or semicolon separated list of strings.

**Comment by davidgraeff** [comment]
@timpur @ThomDietrich @Thalhammer  Can we close this? A map structure is not easily possible via MQTT means and because we decided not to allow external data type standards, this issue is not solvable.

**Comment by Thalhammer** [comment]
@euphi The convention is open for extension by the user, so if you feel like you need more topics in your application you're free to add them (as long as they don't conflict with any homie topics).
But as @davidgraeff already said, a map is not possible without quite complex parsing and tbh the approach you outlined above doesn't feel right anyway.
@davidgraeff I think this can be closed.

**Comment by ThomDietrich** [comment]
I agree that this can't easily and with clear benefits be part of the convention.

**Comment by davidgraeff** [comment]
Alright. Closing this.
