### ISSUE TITLE
How to support multitenancy

### ISSUE THREAD

**Issue by lukecyca** [homieiot/convention#74]
I want to support multiple tenants and I'm wondering how to do that within the convention.

For example I have multiple customers, each with their own devices. It makes sense expose this as a topic hierarchy so that I can correctly set permissions on topic subtrees.

### Option 1: Have multiple base topics

Instead of the "homie" base topic, give each tenant their own:

```
customer1/device-f0e1d2/$homie
customer1/device-a9b8c7/$homie
customer2/device-f0e1d2/$homie
customer2/device-a9b8c7/$homie
```

Nothing in the convention forbids this that I can see. It's a little weird though, because I would want a homie agent that can "see" all the customers' base topics.

### Options 2: Splice in groups
By allowing devices to exist at arbitrary depths, we could support grouping.

```
homie/customer1/device-f0e1d2/$homie
homie/customer1/device-a9b8c7/$homie
homie/customer2/location1/device-f0e1d2/$homie
homie/customer2/location1/device-a9b8c7/$homie
homie/customer2/location2/device-d6e5f4/$homie
```

This is forbidden by the current convention, but is more flexible. If this were allowed in the convention, it wouldn't make device discovery any more difficult. An agent just needs to look for a topic ending in `/$homie` to know that it's found a device.

**Comment by timpur** [comment]
The hard part with option 2 is finding `$homie` using mqtt subs. normally you just sub to `homie/+/$homie` to receive all devices. but with many levels your left to subing many times for each level (`homie/+/+/$homie` ect) or `homie/#`, which gives you every messages and not just devices. So both options ant nice :(. This is an issue ive faced also, and dont know the solution....

**Comment by lukecyca** [comment]
OK, I guess option 1 is preferable. I was under the impression that `homie/#/$homie` was legal (it seems to work for me on mosquitto), but I see now that it is not.

To support option 1, an agent needs to have an option to use multiple base topics (`customer1` and `customer2`) or indeed _all_ base topics by subscribing to `+/+/$homie`.

In fact, even for the simple home-use case, subscribing to `+/+/$homie` would be a great way to discover homie devices without even requiring the base topic to be set at all.

**Comment by ThomDietrich** [comment]
I can see why a sufficient option would be interesting for your use case. The current state of the convention doesn't solve it specifically but imho the "base topic" matches your need -> different bases. So far the choice of a non-"homie" base topic is not described in detail in the convention but there are also no restrictions hindering your from selecting multiple non-defaults. You should also be able to discover all devices due to the unambiguous `+/+/$homie`. I am not sure what you mean by:

>  because I would want a homie agent that can "see" all the customers' base topics.

Regarding a dynamic depth: I also thought about this some time ago. Basically homie could consist of one base topic, an arbitrary number of sublevels, and attributes. No need for "nodes" or "properties". At the current point of the homie convention development I'd rather not start a discussion about that 😅

**Comment by lukecyca** [comment]
>I am not sure what you mean by:

>>because I would want a homie agent that can "see" all the customers' base topics.

By that I just mean that most current homie-compliant agent software is going to take a single "base topic" parameter, and then subscribe only to it. For multitenancy I will need these programs to support watching all base topics simultaneously, which requires them to not only subscribe to `+/+/$homie` instead of `<base>/+/$homie`, but also to do some additional internal housekeeping and not rely on the assumption of a single base topic. This is their problem though, not that of the convention.

**Comment by ingoogni** [comment]
Use semantic topics #57 use multiple brokers (one per tennant?) that can prepend to the topic also in a semantic way.

**Comment by jalmeroth** [comment]
> use multiple brokers (one per tennant?)
+1

This way you could easily map, modify or even filter certain topics.

**Comment by davidgraeff** [comment]
I probably missed the point, but why can't the customer be encoded in the deviceID?
```
homie/device-123456-c1/$homie
homie/device-123456-c2/$homie
```
To group all devices of a specific type, you can use a condition like:
```
homie/+/type=="light"
```

**Comment by ThomDietrich** [comment]
@davidgraeff I believe this is simply a matter of oversight and comfort.
If one wants to e.g. observe all devices by customer 1 in a graphical frontend, that would be as easy as `homie/customer1/#`.

Based on all arguments brought forth it seems like the consensus is to not implement this feature (which would break compatibility). If **You** are interested in a separation of devices, please choose one of the solutions presented above.

**Comment by davidgraeff** [comment]
Please reopen if there is interest in this topic.
