### ISSUE TITLE
Improvements for Homie (V3.1)

### ISSUE THREAD

**Issue by timpur** [homieiot/convention#75]
Anyone have ideas for homie V3.1?
Some Outstanding Discussions:
* Stats implemented as a Node
* https://github.com/homieiot/convention/issues/53
* Bits that didn't get addressed from https://github.com/homieiot/convention/issues/62
* https://github.com/homieiot/convention/issues/51 and https://github.com/homieiot/convention/issues/65
* https://github.com/homieiot/convention/issues/72

**Comment by timpur** [comment]
@marvinroger @zephyrr @ThomDietrich @euphi @nerdfirefighter @ingoogni @lorenwest @tripflex

**Comment by nicola-lunghi** [comment]
https://github.com/homieiot/convention/issues/76

**Comment by nicola-lunghi** [comment]
log feature https://github.com/homieiot/convention/issues/77

**Comment by timpur** [comment]
## Arrays
```
homie/super-car/$nodes → "lights[]"

homie/super-car/lights/$name → "Lights"
homie/super-car/lights/$properties → "intensity"
homie/super-car/lights/$array → "0-1"

homie/super-car/lights/intensity/$name → "Intensity"
homie/super-car/lights/intensity/$settable → "true"
homie/super-car/lights/intensity/$unit → "%"
homie/super-car/lights/intensity/$datatype → "integer"
homie/super-car/lights/intensity/$format → "0:100"

homie/super-car/lights_0/$name → "Back lights"
homie/super-car/lights_0/intensity → "0"
homie/super-car/lights_1/$name → "Front lights"
homie/super-car/lights_1/intensity → "100"
```

I was looking at this example and thought to my self, that actually looks complex to subscribe to via mqtt. Wouldnt it be nicer to do this:
```
homie/super-car/lights/0/$name → "Back lights"
homie/super-car/lights/0/intensity → "0"
homie/super-car/lights/1/$name → "Front lights"
homie/super-car/lights/1/intensity → "100"
```
Thus you onlt have to sub to `homie/super-car/lights/#` to get all the node topics, since there all hirarical now.

Maybe also:
```
homie/super-car/lights/elements/0/$name → "Back lights"
homie/super-car/lights/elements/0/intensity → "0"
homie/super-car/lights/elements/1/$name → "Front lights"
homie/super-car/lights/elements/1/intensity → "100"
```

Just ideas, tell me your thoughts?

**Comment by marvinroger** [comment]
`homie/super-car/lights/0/$name` looks like a `$name` attribute of the `0` property of the `lights` node.

**Comment by ThomDietrich** [comment]
My thought exactly.

Remember that the underscore character is reserved for arrays in topic ids.

I'd suggest to discuss this in a specific issue.

**Comment by ThomDietrich** [comment]
Also could you create an issue to start discussion of the stats improvement?

**Comment by nerdfirefighter** [comment]
why is lights an array? is it because now at the nodes layer its by node type?

My usage of a range/array is when i have a light strip where i refer to strip[] which is an array of led 0- length of strip. each led in the strip does not have a name they only have a value (which most of the time is a Red:Green:Blue string). i dont think having an name value for each array element is appropriate. if you need a name is should be its own node not a range.

**Comment by ThomDietrich** [comment]
@nerdfirefighter `$name` just as most other attributes is not mandatory.

**Comment by timpur** [comment]
sorry moved to https://github.com/homieiot/convention/issues/90

**Comment by nicola-lunghi** [comment]
Can we create a "development" or testing branch and start putting the "approved" modification in it to see if this is coherent?
for example the "optional" arguments

**Comment by timpur** [comment]
Have you guys seen https://iot.mozilla.org/wot/, @ThomDietrich

**Comment by davidgraeff** [comment]
Closing this umbrella issue. See #62.
