### ISSUE TITLE
Implement a way to set up report interval

### ISSUE THREAD

**Issue by nicola-lunghi** [homieiot/convention#80]
There are a lot of cases where I need to set a time interval to report the value of a parameter

for example for a temperature reading

    homie/super-car/engine/temperature/$name → "Engine temperature"
    homie/super-car/engine/temperature/$settable → "false"
    homie/super-car/engine/temperature/$unit → "°C"
    homie/super-car/engine/temperature/$datatype → "float"
    homie/super-car/engine/temperature/$format → "-20:120"
    homie/super-car/engine/temperature → "21.5"

can we add a 

   homie/super-car/engine/temperature/$report-interval → "0"

that:
* if set to 0 stop the variable reporting
* if set to a positive value (in seconds) report that variable with that interval

so if from the controller i send

    homie/super-car/engine/temperature/$report-interval/set → "10"

then I receive first a confirmation that the value has been set and immediatly the current value

    homie/super-car/engine/temperature/$report-interval → "10"
    homie/super-car/engine/temperature → "21.5"

then I receive the new value every 10 seconds

    homie/super-car/engine/temperature → "21.5"
    ...
    homie/super-car/engine/temperature → "21.5"

to stop it I set again the timer to 0

    homie/super-car/engine/temperature/$report-interval/set → "0"
    homie/super-car/engine/temperature/$report-interval → "0"

**Comment by nicola-lunghi** [comment]
basically this implements the same that the interval property is doing for stats but permit a more general implementation (but with getter and setters)

**Comment by ingoogni** [comment]
See discussion #53

**Comment by nicola-lunghi** [comment]
Ok so its already addressed
