### ISSUE TITLE
Add a parameter to know if firmware update is supported

### ISSUE THREAD

**Issue by nicola-lunghi** [homieiot/convention#84]
Parameter to know if firmware upgrade over the air is supported

    homie/super-car/$fw/upgrade-supported → "true"

**Comment by fermuch** [comment]
Since each component updates it's own way, doesn't it make more sense to add it as an `$implementation`, as the esp8266 library does?

**Comment by ThomDietrich** [comment]
@fermuch raises a valid point. OTA is not part of the convention. The more general question here is hence: Should it be? I'd be inclined to say no as this functionality is not relevant for interoperability.

**Comment by timpur** [comment]
I would have to agree with the above answers, homie has a core purpose and cant be streched out to fit every snario, It is not for homie to say if you must suport OTA. For some implementations this doesnt make sense at all. This is why it is located in `$implementation`.
