### ISSUE TITLE
Slim down required Homie topics

### ISSUE THREAD

**Issue by davidgraeff** [homieiot/convention#86]
I thought about the effort and additional memory usage to make an existing MQTT embedded client  Homie compatible (in this case [ESPeasy](https://github.com/letscontrolit/ESPEasy/issues/1314#issuecomment-384378383)). I noticed that Homie actually requires a lot of topics to be implemented.

Why is it required to have "$localip", "$mac", "$fw/name", "$implementation", "$stats" and other attributes.? Can those attributes be marked as "optional" or "recommended" instead?

You have to thing of what a controller essentially needs from a homie device. That is:
* auto-discovery of the device, the nodes, the properties,
* the property types, formats and units,
* the device's name and state.

Everything else can be omitted for a working controller<->device communication. Right now such an implementation would violate the spec though.

**Comment by nicola-lunghi** [comment]
+1

**Comment by ThomDietrich** [comment]
I agree and was discussing this with @marvinroger before. We started with #48 but wanted to discuss further optional topics.
Marvin: Wdyt?

**Comment by davidgraeff** [comment]
Oh. This is a duplicate of #45. Sorry for that.

**Comment by ThomDietrich** [comment]
Indeed. Let's move the discussion over there then. Would you add your OP and some additional comments over there?
