### ISSUE TITLE
Duplicate issues

### ISSUE THREAD

**Issue by davidgraeff** [homieiot/convention#91]
I'm sorry to open an issue for this, but it would help a lot if the maintainers could close duplicate issues instead of keeping them open and if issues could be tagged. Issues should be partly renamed as well.

There are multiple issues about Homie 3.x planning. 2 issues about the interval attribute and so on.

Ehm and this one can be closed now, of course :)

**Comment by timpur** [comment]
Noted

**Comment by ThomDietrich** [comment]
@timpur @marvinroger I added a few labels yesterday. Those are just a first step. Feel free to add new ones or refine the existing ones.
